name: Flask API Integration Tests

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches:
      - main
      - master


jobs:
  integration-tests:
    runs-on: ubuntu-latest


    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Start Flask App in Background
        run: |
          nohup python app.py > flask.log 2>&1 &
          sleep 10

      - name: Check if Flask is Running
        run: |
          curl http://127.0.0.1:5000/info?id=1 || (echo "Flask app failed to start!" && cat flask.log && exit 1)

      - name: Install Newman CLI
        run: |
          npm install -g newman

      - name: Run Postman Collection Tests
        run: |
          newman run tests/Flask\ API\ Test.postman_collection.json --reporters cli,junit --reporter-junit-export newman-report.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.xml

