name: Flask API Integration Tests

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches:
      - main
      - master


jobs:
  integration-tests:
    runs-on: ubuntu-latest


    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Start Flask App in Background
        run: |
          nohup python app.py &
          sleep 5

      - name: Install Newman CLI
        run: |
          npm install -g newman

      - name: Run Postman Collection Tests
        run: |
          newman run tests/Flask API Test.postman_collection.json --reporter-cli

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.xml

